// Back to top button
(function(){$(document).ready(function(){return $(window).scroll(function(){return $(window).scrollTop()>600?$("#back-to-top").addClass("show"):$("#back-to-top").removeClass("show")}),$("#back-to-top").click(function(){return $("html,body").animate({scrollTop:"0"})})})}).call(this);
// Search Hery Setiaji
$(function(){$(".searchbutton").on("click",function(){$(".Hery-Search").addClass("active").find(".search").focus()});$(".Hery-Search").on("click",function(){$(this).find(".search").focus()});$("#close").on("click",function(){$(".Hery-Search").removeClass("active")})});
// Menu Top
$(document).ready(function(){var str=location.href.toLowerCase();$('.top-menunavi ul li a').each(function(){if(str.indexOf(this.href.toLowerCase())>-1){$("li.highlight").removeClass("highlight");$(this).parent().addClass("highlight")}})})
$(function(){var pull=$('#pull');menu=$('.top-menunavi ul');menuHeight=menu.height();$(pull).on('click',function(e){e.preventDefault();menu.slideToggle()});$(window).resize(function(){var w=$(window).width();if(w>320&&menu.is(':hidden')){menu.removeAttr('style')}})});
// Main Menu
var ww=document.body.clientWidth;$(document).ready(function(){$(".nav li a").each(function(){if($(this).next().length>0){$(this).addClass("parent")}});$(".menu-slide").click(function(e){e.preventDefault();$(this).toggleClass("active");$(".nav").toggle()});adjustMenu()});$(window).bind("resize orientationchange",function(){ww=document.body.clientWidth;adjustMenu()});var adjustMenu=function(){if(ww<768){$(".menu-slide").css("display","inline-block");if(!$(".menu-slide").hasClass("active")){$(".nav").hide()}else{$(".nav").show()}$(".nav li").unbind("mouseenter mouseleave");$(".nav li a.parent").unbind("click").bind("click",function(e){e.preventDefault();$(this).parent("li").toggleClass("hover")})}else if(ww>=768){$(".menu-slide").css("display","none");$(".nav").show();$(".nav li").removeClass("hover");$(".nav li a").unbind("click");$(".nav li").unbind("mouseenter mouseleave").bind("mouseenter mouseleave",function(){$(this).toggleClass("hover")})}}
// Mantabs BLOGG
!function(a){"use strict";var b=function(b,c){var d=this;d.element=b,d.$element=a(b),d.HStabs=d.$element.children(),d.options=a.extend({},a.fn.SHStabs.defaults,c),d.current_tab=0,d.init()};b.prototype={init:function(){var a=this;a.HStabs.length&&(a.build(),a.buildTabMenu())},build:function(){var b=this,c=b.options,d=c.tab_text_el,e=c.container_class;b.tab_names=[],b.$wrapper=b.$element.wrapInner('<div class="'+e+'" />').find("."+e),b.HStabs.wrapAll('<div class="'+c.HStabs_container_class+'" />'),b.HStabs.each(function(c,e){var f,g=a(e),h=d;f=g.find(h).filter(":first").hide().text(),b.tab_names.push(f)}),a.isFunction(c.onReady)&&c.onReady.call(b.element)},buildTabMenu:function(){for(var b,c=this,d=c.options,e=d.HStabsmenu_el,f=c.tab_names,g="<"+e+' class="'+d.HStabsmenu_class+'">',h=0,i=f.length,j=function(){var a=arguments;return d.tmpl.HStabsmenu_tab.replace(/\{[0-9]\}/g,function(b){var c=Number(b.replace(/\D/g,""));return a[c]||""})};i>h;h++)g+=j(h+1,f[h]);g+="</"+e+">",c.$HStabs_menu=a(g).prependTo(c.$wrapper),b=c.$HStabs_menu.find(":first")[0].nodeName.toLowerCase(),c.$HStabs_menu.on("click",b,function(b){var d=a(this),e=d.index();c.show(e),b.preventDefault()}).find(":first").trigger("click")},show:function(b){var c=this,d=c.options,e=d.active_tab_class;c.HStabs.hide().filter(":eq("+b+")").show(),c.$HStabs_menu.children().removeClass(e).filter(":eq("+b+")").addClass(e),a.isFunction(d.onHStabselect)&&b!==c.current_tab&&d.onHStabselect.call(c.element,b),c.current_tab=b},destroy:function(){var a=this,b=a.options.tab_text_el;a.$HStabs_menu.remove(),a.HStabs.unwrap().unwrap(),a.HStabs.removeAttr("style"),a.HStabs.children(b+":first").removeAttr("style"),a.$element.removeData("SHStabs")}},a.fn.SHStabs=function(c,d){return this.each(function(){var e,f=a(this),g=f.data("SHStabs");e="object"==typeof c&&c,g||f.data("SHStabs",g=new b(this,e)),"string"==typeof c&&g[c](d)})},a.fn.SHStabs.defaults={container_class:"HStabs",HStabs_container_class:"HStabs-content",active_tab_class:"active-tab",tab_text_el:"h1, h2, h3, h4, h5, h6",HStabsmenu_class:"HStabs-menu",HStabsmenu_el:"ul",tmpl:{HStabsmenu_tab:'<li class="tab-{0}"><span>{1}</span></li>'},onHStabselect:null}}(window.jQuery,window,document);
// Search Result
function SearchBlogHery(){var e=$(".search").val(),t=$(".search-item").length+1;if(e.length>=1){$(".search-content").slideDown(),$(".search-filter").attr("data-query",e),$(".search-result span").slideDown().html("Searching ...");var r="/feeds/posts/default?max-results=12&start-index="+t+"&alt=json&q="+e;$.ajax({type:"GET",url:r,async:!0,contentType:"application/json",dataType:"jsonp",success:function(t){$(".query-result").slideUp(),doSearch(t,e)}})}else $(".search-content").slideUp()}function doSearch(e,t){if(e.feed.entry){for(var r=0;r<e.feed.entry.length;r++){for(var n=0;n<e.feed.entry[r].link.length;n++)if("alternate"==e.feed.entry[r].link[n].rel){var a=e.feed.entry[r].link[n].href;break}try{var s=e.feed.entry[r].media$thumbnail.url}catch(i){var s="http://3.bp.blogspot.com/-ltyYh4ysBHI/U04MKlHc6pI/AAAAAAAADQo/PFxXaGZu9PQ/w100-h100-c/no-image.png"}var c=e.feed.entry[r].title.$t,h='<div class="search-item"><img src="'+s+'"/><a href="'+a+'" target="_blank">'+c+"</a></div>";$(".search-result").append(h)}$(".search-result span").slideUp(function(){$(".queryword").html("Show results for:<b>"+t+"</b>"),$(".query-result").slideDown()})}else $(".search-result span").slideDown().html("Search no detected!"),$(".query-result").slideUp()}$(".searchmein").submit(function(){return $(".search-item").remove(),SearchBlogHery(),!1}),$(".close-search").click(function(){$(".search-content").slideUp()}),$(".query-result").click(function(){$(".query-result").slideUp(),SearchBlogHery()});
// Sticky Widget
$(function(){if($('#HTML9').length){var o=$('#HTML9'),t=$('#HTML9').offset().top,i=$('#HTML9').height();$(window).scroll(function(){var s=$("#footer-wrapper").offset().top-i-70,f=$(window).scrollTop();if(f>t?o.css({position:"fixed",top:70}):o.css("position","static"),f>s){var n=s-f;o.css({top:n})}})}});
